This is the code and data files for all terrorism related projects. The data is sourced from the Global Terrorism Database created and maintained by the University of Maryland.

# Reference

National Consortium for the Study of Terrorism and Responses to Terrorism (START). (2017). Global Terrorism Database [Data file]. Retrieved from https://www.start.umd.edu/gtd